"use client";

import { useState } from "react";

type Item = { sourceCode: string; imageSourceId: string; imagePreviewUrl: string; status: "MATCHED" | "NOT_FOUND"; dish: { id: string; name: string } | null };
type Summary = { sourceRows: number; matched: number; unchanged: number; notFound: number };

export default function RniImageSync() {
  const [items, setItems] = useState<Item[]>([]); const [summary, setSummary] = useState<Summary | null>(null); const [reason, setReason] = useState("Đồng bộ mã ảnh tham chiếu từ cơ sở dữ liệu món ăn RNI."); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const preview = async () => { setBusy(true); setItems([]); setSummary(null); const response = await fetch("/api/admin/data/images/rni-sync-preview", { method: "POST" }); const data = await response.json(); setBusy(false); if (response.ok) { setItems(data.items); setSummary(data.summary); setMessage("Đã quét ảnh RNI. Hãy kiểm tra trước khi xác nhận."); } else setMessage(data.error ?? "Không thể quét ảnh RNI."); };
  const commit = async () => { const matched = items.filter((item) => item.status === "MATCHED" && item.dish).map((item) => ({ id: item.dish!.id, sourceCode: item.sourceCode, imageSourceId: item.imageSourceId })); if (!matched.length) return setMessage("Không có món RNI khớp mã để cập nhật."); setBusy(true); const response = await fetch("/api/admin/data/images/rni-commit", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ items: matched, reason }) }); const data = await response.json(); setBusy(false); setMessage(response.ok ? `Đã lưu ${data.updated} mã ảnh RNI; bỏ qua ${data.skipped} dòng.` : (data.error ?? "Chưa thể lưu ảnh RNI.")); };
  return <section className="rounded-xl border-2 border-[#386f99] bg-[#f3f9fc] p-5"><h2 className="text-xl font-semibold">Đồng bộ ảnh công thức RNI</h2><p className="mt-1 text-sm">Không cần Excel. Ảnh RNI được lưu bằng mã ảnh chính chủ, không lưu file ảnh nặng vào database. Mã món được đối chiếu chính xác trước khi cập nhật.</p><button type="button" onClick={() => void preview()} disabled={busy} className="mt-4 rounded bg-[#17496e] px-4 py-2 font-semibold text-white disabled:opacity-60">{busy ? "Đang quét RNI…" : "Quét ảnh từ RNI"}</button>{message && <p className="mt-3 rounded border bg-white p-3 text-sm">{message}</p>}{summary && <div className="mt-4 grid gap-2 text-sm sm:grid-cols-4"><p className="border bg-white p-2"><b>{summary.sourceRows}</b><br />có ảnh</p><p className="border bg-white p-2"><b>{summary.matched}</b><br />mã khớp</p><p className="border bg-white p-2"><b>{summary.unchanged}</b><br />đã giống</p><p className="border bg-white p-2"><b>{summary.notFound}</b><br />không thấy</p></div>}{items.length > 0 && <><label className="mt-4 block font-semibold">Lý do cập nhật hàng loạt<textarea value={reason} onChange={(event) => setReason(event.target.value)} className="mt-1 min-h-20 w-full rounded border px-3 py-2" /></label><div className="mt-3 max-h-64 overflow-auto border bg-white"><table className="min-w-full text-sm"><thead className="sticky top-0 bg-[#e8f3f8]"><tr><th className="p-2 text-left">Mã</th><th className="p-2 text-left">Tên công thức</th><th className="p-2 text-left">Kết quả</th><th className="p-2 text-left">Ảnh</th></tr></thead><tbody>{items.slice(0, 150).map((item) => <tr key={item.sourceCode} className="border-t"><td className="p-2">{item.sourceCode}</td><td className="p-2">{item.dish?.name ?? "—"}</td><td className="p-2">{item.status === "MATCHED" ? "Khớp" : "Không có mã"}</td><td className="p-2"><a href={item.imagePreviewUrl} target="_blank" rel="noreferrer" className="text-[#17496e] underline">Xem ảnh</a></td></tr>)}</tbody></table></div><button type="button" onClick={() => void commit()} disabled={busy} className="mt-4 rounded bg-[#17496e] px-5 py-2.5 font-semibold text-white disabled:opacity-60">Xác nhận cập nhật {summary?.matched ?? 0} ảnh RNI</button></>}</section>;
}
