"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export default function LoginForm() {
  const router = useRouter(); const [mode,setMode]=useState<"login"|"register">("login"); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const r=await fetch(mode==="login"?"/api/auth/login":"/api/auth/register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(mode==="login"?{email,password}:{displayName:name,email,password})});const d=await r.json().catch(()=>({}));if(r.ok){router.push("/");router.refresh()}else setMessage(d.error??"Không thể thực hiện yêu cầu.");setBusy(false)}
  const registering=mode==="register";
  return <section className="mx-auto max-w-md rounded-xl border-2 border-[#123c36] bg-white p-6 shadow-sm"><p className="text-xs font-semibold tracking-[.16em] text-[#123c36]">TÀI KHOẢN HỆ THỐNG</p><h1 className="mt-1 text-3xl font-semibold">{registering?"Tạo tài khoản":"Đăng nhập"}</h1><p className="mt-2 text-sm text-neutral-900">{registering?"Tự đặt mật khẩu để lưu khẩu phần, bản nháp thực phẩm và dữ liệu làm việc của riêng bạn.":"Đăng nhập để tiếp tục các dữ liệu đã lưu."}</p><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={()=>{setMode("login");setMessage("")}} className={`rounded border-2 px-3 py-2 font-semibold ${!registering?"border-[#123c36] bg-[#123c36] text-white":"border-[#8fa99e]"}`}>Đăng nhập</button><button type="button" onClick={()=>{setMode("register");setMessage("")}} className={`rounded border-2 px-3 py-2 font-semibold ${registering?"border-[#123c36] bg-[#123c36] text-white":"border-[#8fa99e]"}`}>Đăng ký mới</button></div><form onSubmit={submit} className="mt-5 space-y-4">{registering&&<label className="block font-semibold">Họ và tên<input required value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded border-2 border-[#8fa99e] px-3 py-2"/></label>}<label className="block font-semibold">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1 w-full rounded border-2 border-[#8fa99e] px-3 py-2"/></label><label className="block font-semibold">Mật khẩu{registering&&<span className="ml-1 text-sm font-normal">(tối thiểu 10 ký tự)</span>}<input required minLength={registering?10:undefined} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full rounded border-2 border-[#8fa99e] px-3 py-2"/></label><button disabled={busy} className="w-full rounded bg-[#123c36] px-4 py-2.5 font-semibold text-white">{busy?"Đang xử lý…":registering?"Tạo tài khoản và bắt đầu lưu dữ liệu":"Đăng nhập"}</button></form>{message&&<p className="mt-4 rounded border border-[#8a2323] bg-[#fff5f5] p-3 font-semibold">{message}</p>}<p className="mt-5 text-xs text-neutral-700">Tài khoản tự đăng ký là Người dùng chuyên môn. Quyền Quản trị và Biên tập dữ liệu nguồn do Admin phân công.</p></section>;
}
