import Link from "next/link";

function Card({ number, title, children }: { number: string; title: string; children: React.ReactNode }) {
  return <section className="overflow-hidden rounded-lg border-2 border-[#7f948d] bg-white"><div className="flex items-center gap-3 border-b-2 border-[#123c36] bg-[#edf4f0] px-5 py-3"><span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-[#123c36] text-sm font-semibold text-white">{number}</span><h2 className="text-xl font-semibold">{title}</h2></div><div className="p-5 text-neutral-900">{children}</div></section>;
}

export default function HuongDanPage() {
  return <div className="flex flex-col gap-5"><section className="border-b-2 border-[#123c36] pb-4"><p className="text-xs font-semibold tracking-[0.16em] text-[#123c36]">HƯỚNG DẪN SỬ DỤNG · THEO LUỒNG SCRIPT CŨ</p><h1 className="mt-1 text-3xl font-semibold">Lập và phân tích khẩu phần từng bước</h1><p className="mt-2 max-w-4xl text-neutral-900">Luồng thao tác giữ theo app script: nhập hồ sơ → lập bữa/món/thực phẩm → kiểm tra kết quả → xuất phiếu. Website bổ sung phân quyền, kiểm duyệt và đối chiếu dữ liệu rõ ràng hơn.</p><Link href="/tinh-khau-phan" className="mt-4 inline-flex rounded-md bg-[#123c36] px-5 py-3 font-semibold text-white">Bắt đầu nhập khẩu phần →</Link></section>

    <Card number="1" title="Chọn đúng chế độ nhập"><div className="grid gap-4 md:grid-cols-2"><div className="border-l-4 border-[#123c36] bg-[#f5faf7] p-4"><h3 className="font-semibold">Khẩu phần 24 giờ</h3><p className="mt-1">Dùng khi hỏi người bệnh/người chăm sóc đã ăn gì. Nhập lượng <b>đã ăn</b>; khi CSDL có tỷ lệ thải bỏ, hệ thống tự quy đổi về lượng nguyên liệu để tính.</p></div><div className="border-l-4 border-[#73540d] bg-[#fffdf6] p-4"><h3 className="font-semibold">Lập thực đơn</h3><p className="mt-1">Dùng khi xây kế hoạch ăn. Nhập lượng nguyên liệu sống sạch để quy đổi phần ăn được và dùng cho xuất kho/mua nguyên liệu.</p></div></div><p className="mt-4 text-sm">Nên chia đủ các bữa thực tế: sáng, phụ sáng, trưa, phụ chiều, tối, phụ tối. Bữa không ăn thì không cần tạo.</p></Card>

    <Card number="2" title="Tạo bữa, món và tìm thực phẩm"><ol className="list-decimal space-y-2 pl-5"><li>Bấm <b>+ Thêm bữa ăn</b>, sau đó <b>+ Món</b> và chọn món đang làm việc.</li><li>Tại khu <b>Tìm &amp; thêm</b>, chọn tab <b>Thực phẩm</b> hoặc <b>Món ăn theo công thức</b>; có thể lọc theo loại, nguồn, nhóm thực phẩm, nhóm tuổi và chế độ bệnh lý.</li><li>Bấm vào kết quả để thêm vào món đang chọn. Với công thức món ăn, hệ thống chỉ thêm các nguyên liệu đã liên kết được với Food.</li><li>Dùng tên cụ thể: “cá chép”, “gạo tẻ”, “thịt lợn nạc” thay vì ghi chung chung “cá”, “gạo”, “thịt”.</li></ol><p className="mt-4 rounded border border-[#a77b10] bg-[#fff8df] p-3 text-sm"><b>Phân biệt quan trọng:</b> món ăn trong Food có số liệu dinh dưỡng /100 g; món ăn theo công thức có nguyên liệu. Hãy đọc nhãn của từng kết quả trước khi dùng.</p></Card>

    <Card number="3" title="Chưa có thực phẩm trong CSDL?"><p>Bấm <b>＋ Thực phẩm mới</b> ngay trong màn nhập. Điền tên và số liệu /100 g, rồi bấm <b>Thêm ngay vào khẩu phần</b>. Dòng tạm được dùng ngay cho phép tính của phiếu hiện tại.</p><p className="mt-3">Nếu muốn dùng chung về sau, tích <b>Gửi bản nháp để kiểm duyệt</b>, thêm mô tả và nguồn tham khảo. Quản trị viên xem bản nháp, có thể duyệt hoặc yêu cầu bổ sung.</p><p className="mt-3 rounded border border-[#8a2323] bg-[#fff5f5] p-3 text-sm"><b>Không tự cập nhật dữ liệu nguồn:</b> duyệt bản nháp không tự ghi vào Food/Dish chính. Điều này bảo vệ luồng dữ liệu đang được đối chiếu riêng.</p></Card>

    <Card number="4" title="AI nhập nhanh: dán mô tả, rồi kiểm tra"><p>Khung <b>AI hỗ trợ nhập liệu</b> nhận mô tả tự nhiên và bóc tách thành bữa → món → thực phẩm. Ví dụ:</p><pre className="mt-3 overflow-x-auto border border-[#7f948d] bg-[#f7faf8] p-3 text-sm whitespace-pre-wrap">Sáng: 1 tô phở bò 350 g (bánh phở 150 g, thịt bò 60 g, hành lá 5 g).{"\n"}Trưa: cơm 200 g, cá chép kho 80 g, rau muống luộc 100 g.</pre><ul className="mt-3 list-disc space-y-1 pl-5"><li>AI chỉ lấy lượng đã ghi rõ; lượng không rõ sẽ hiển thị “Chưa rõ”, không tự ước lượng.</li><li>Dòng khớp CSDL mới được chọn sẵn. Dòng chưa khớp phải tìm lại thủ công hoặc thêm thực phẩm mới.</li><li>Xem trước, bỏ/sửa dòng chưa đúng, rồi bấm <b>Thêm các dòng đã kiểm tra vào khẩu phần</b>.</li><li>Có thể dùng key Gemini riêng cho một phiên, hoặc key chung sau khi đăng nhập. Không đưa thông tin định danh không cần thiết của người bệnh vào ô AI.</li></ul></Card>

    <Card number="5" title="Đọc kết quả và các bảng đối chiếu"><div className="grid gap-4 lg:grid-cols-2"><div><h3 className="font-semibold">Tổng hợp khẩu phần</h3><ul className="mt-2 list-disc space-y-1 pl-5"><li><b>Vàng:</b> tổng một món.</li><li><b>Xanh nhạt:</b> tổng một bữa.</li><li><b>Xanh đậm:</b> tổng cả ngày.</li><li><b>Dữ liệu gốc /100 g:</b> kiểm tra phép tính theo công thức giá trị × khối lượng /100.</li></ul></div><div><h3 className="font-semibold">Phân tích chuyên môn</h3><ul className="mt-2 list-disc space-y-1 pl-5"><li>Đối chiếu năng lượng và P/L/G với hồ sơ đã nhập.</li><li>Vi chất, nhóm thực phẩm, đơn vị ăn và quy đổi xuất kho là các bảng có thể bật/tắt.</li><li>10 biểu đồ dùng để nhìn phân bố; luôn đọc bảng số liệu kèm theo biểu đồ.</li></ul></div></div><p className="mt-4 text-sm">Kết quả là công cụ hỗ trợ. Với chất thiếu dữ liệu, tổng có thể thấp hơn thực tế; cần xem ghi chú độ đầy đủ trước khi kết luận chuyên môn.</p></Card>

    <Card number="6" title="Lập phiếu, xuất và lưu"><ol className="list-decimal space-y-2 pl-5"><li>Trong phần Kết quả, chọn các nhóm bảng cần xem để phiếu không quá dài.</li><li>Bấm <b>Thiết lập / In PDF</b>, điền người được đánh giá, người lập, vai trò, đơn vị và diễn biến bệnh lý/theo dõi.</li><li>In PDF theo khổ A4 hoặc xuất Excel để đối chiếu tiếp.</li><li>Khi chức năng tài khoản được kích hoạt sau migration, phiếu có thể được lưu/mở lại theo từng người dùng.</li></ol></Card>

    <section className="rounded-lg border-2 border-[#a77b10] bg-[#fffdf6] p-5"><h2 className="text-xl font-semibold">Nguyên tắc dữ liệu và an toàn</h2><ul className="mt-2 list-disc space-y-1 pl-5 text-neutral-900"><li>Mọi số liệu dinh dưỡng trong tra cứu được hiển thị theo 100 g, trừ khi ghi chú khác.</li><li>Loại thực phẩm gồm: TS (tươi sống), CB (chế biến), MA (món ăn), SP (sản phẩm).</li><li>Kiểm tra nguồn, khối lượng, phần ăn được và tỷ lệ thải bỏ trước khi dùng cho quyết định chuyên môn.</li><li>Công cụ không thay thế thăm khám, đánh giá lâm sàng hoặc chỉ định điều trị của người có chuyên môn.</li></ul></section></div>;
}
