import Link from "next/link";

export const metadata = { title: "Về hệ thống | Dinh dưỡng 2598" };

export default function VeHeThongPage() {
  return <div className="flex flex-col gap-5">
    <section className="border-b-2 border-[#123c36] pb-4"><p className="text-xs font-semibold tracking-[0.16em] text-[#123c36]">SÁNG KIẾN CẢI TIẾN</p><h1 className="mt-1 text-3xl font-semibold">Về công cụ Dinh dưỡng 2598</h1><p className="mt-2 max-w-4xl text-neutral-900">Dinh dưỡng 2598 là sản phẩm của sáng kiến cải tiến tại Bệnh viện Đa khoa Nam Liên Chiểu, Sở Y tế thành phố Đà Nẵng. Hệ thống hỗ trợ tra cứu, lập khẩu phần và đối chiếu dinh dưỡng, kế thừa luồng nghiệp vụ của Google Apps Script trước đây.</p><p className="mt-2 max-w-4xl text-sm text-neutral-800">Đây là công cụ hỗ trợ nghiệp vụ; không thay thế thăm khám, chẩn đoán hoặc chỉ định điều trị của nhân viên y tế.</p></section>
    <section className="rounded-lg border-2 border-[#7f948d] bg-white p-5"><h2 className="text-xl font-semibold">Chức năng chính</h2><ul className="mt-2 list-disc space-y-1 pl-5"><li>Tra cứu thực phẩm, sản phẩm, món ăn có số liệu và món ăn theo công thức.</li><li>Lập thực đơn hoặc điều tra khẩu phần 24 giờ; quy đổi khối lượng ăn được và nguyên liệu.</li><li>Đối chiếu năng lượng, P/L/G, vi chất, mã chế độ ăn, thể trạng và biểu đồ phân tích.</li><li>AI hỗ trợ bóc tách mô tả thành bản xem trước; người dùng xác nhận trước khi thêm.</li><li>Xuất phiếu đánh giá, đề xuất dữ liệu và kiểm duyệt bằng khu quản trị riêng.</li></ul></section>
    <section className="rounded-lg border-2 border-[#123c36] bg-[#f7faf8] p-5"><h2 className="text-xl font-semibold">Căn cứ khuyến nghị và đánh giá</h2><ul className="mt-2 list-disc space-y-1 pl-5"><li>Bảng thành phần thực phẩm Việt Nam – Viện Dinh dưỡng.</li><li>Khuyến nghị dinh dưỡng theo tuổi, giới và hoạt động từ dữ liệu Viện Dinh dưỡng đang có trong hệ thống.</li><li>QĐ 2598/QĐ-BYT – Hướng dẫn quy trình kỹ thuật về Dinh dưỡng lâm sàng (chi tiết tại Tài liệu tham khảo).</li><li>TT 18/2020/TT-BYT – mã chế độ ăn bệnh lý.</li><li>WHO Child Growth Standards 2006 – đối chiếu tăng trưởng trẻ em.</li><li>Mifflin–St Jeor (1990) – ước tính nhu cầu năng lượng ở người lớn.</li></ul></section>
    <section className="rounded-lg border-2 border-[#7f948d] bg-white p-5"><h2 className="text-xl font-semibold">Nguồn và giới hạn dữ liệu</h2><ul className="mt-2 list-disc space-y-1 pl-5"><li>Dữ liệu Food/Dish được quản lý theo luồng nguồn riêng; hệ thống không tự ý chỉnh sửa bản gốc.</li><li>Một số chất chưa đủ số liệu ở mọi thực phẩm. Tổng kết quả có thể thấp hơn thực tế và luôn cần xem ghi chú đi kèm.</li><li>Các quy đổi, biểu đồ và AI là công cụ hỗ trợ chuyên môn.</li></ul></section>
    <div className="flex flex-wrap gap-3"><Link href="/tai-lieu-tham-khao" className="rounded-md border-2 border-[#123c36] bg-white px-4 py-2 font-semibold text-[#123c36]">Tài liệu tham khảo</Link><Link href="/huong-dan" className="rounded-md border-2 border-[#123c36] bg-white px-4 py-2 font-semibold text-[#123c36]">Đọc hướng dẫn sử dụng</Link><Link href="/tinh-khau-phan" className="rounded-md bg-[#123c36] px-4 py-2 font-semibold text-white">Mở tính khẩu phần</Link></div>
  </div>;
}
