import Link from "next/link";

export const metadata = { title: "Tài liệu tham khảo | Dinh dưỡng 2597", description: "Danh mục văn bản và tài liệu chuyên môn được dùng để tham khảo trong Dinh dưỡng 2597." };

const references = [
  { title: "Quyết định 2598/QĐ-BYT ngày 18/08/2025", publisher: "Bộ Y tế", tag: "Văn bản nền tảng", note: "Ban hành tài liệu chuyên môn “Hướng dẫn quy trình kỹ thuật về Dinh dưỡng lâm sàng”, gồm 36 quy trình kỹ thuật. Đây là căn cứ về quy trình kỹ thuật, không phải bảng nhu cầu dinh dưỡng hay biểu mẫu điều tra khẩu phần 24 giờ.", href: "https://syt.bacninh.gov.vn/documents/184573/14187101/2025.08.19.tri%E1%BB%83n%20khai%20h%C6%B0%E1%BB%9Bng%20d%E1%BA%ABn%20quy%20tr%C3%ACnh%20k%E1%BB%B9%20thu%E1%BA%ADt%20v%E1%BB%81%20dinh%20d%C6%B0%E1%BB%A1ng%20l%C3%A2m%20s%C3%A0ng__19082025171940_signed.pdf" },
  { title: "Quyết định 1986/QĐ-BYT ngày 01/07/2026", publisher: "Cục Quản lý Khám, chữa bệnh – Bộ Y tế", tag: "Cập nhật hiệu lực", note: "Sửa Điều 2 của QĐ 2598/QĐ-BYT: tài liệu Hướng dẫn quy trình kỹ thuật về Dinh dưỡng lâm sàng được áp dụng tại cơ sở khám bệnh, chữa bệnh từ ngày 01/01/2028. Mốc này được ưu tiên khi đối chiếu hiệu lực áp dụng.", href: "https://kcb.vn/tin-tuc/sua-doi-quy-dinh-ve-hieu-luc-thi-hanh-thoi-diem-ap-dung-tai-mot-so-quyet-dinh-cua-bo-truong-bo-y-te-ban-hanh-tai-lieu-ch.html" },
  { title: "Hướng dẫn chế độ ăn bệnh viện", publisher: "Bộ Y tế · QĐ 2879/QĐ-BYT ngày 10/08/2006", tag: "Chế độ ăn bệnh viện", note: "Tài liệu nền về nguyên tắc xây dựng chế độ ăn bệnh viện. Dùng để tham khảo bối cảnh thực hành; cần đối chiếu thêm quy định và hướng dẫn mới hơn trước khi áp dụng tại cơ sở.", href: "https://thuvienphapluat.vn/van-ban/The-thao-Y-te/Quyet-dinh-2879-QD-BYT-nam-2006-huong-dan-che-do-an-benh-vien-do-Bo-truong-Bo-Y-te-ban-hanh-2377.aspx" },
  { title: "Khuyến nghị cho người Việt Nam – Nhu cầu dinh dưỡng", publisher: "Viện Dinh dưỡng", tag: "Nhu cầu dinh dưỡng", note: "Nguồn tham khảo cho nhu cầu dinh dưỡng theo nhóm đối tượng. Website chỉ dùng số liệu đã được cấu hình và luôn hiển thị căn cứ để người sử dụng kiểm tra.", href: "https://viendinhduong.vn/" },
  { title: "WHO guideline: breastfeeding in maternity and newborn facilities (2017)", publisher: "World Health Organization", tag: "Nuôi con bằng sữa mẹ", note: "Hướng dẫn bảo vệ, thúc đẩy và hỗ trợ nuôi con bằng sữa mẹ tại các cơ sở cung cấp dịch vụ sản khoa và sơ sinh.", href: "https://www.who.int/publications/i/item/9789241550086" },
  { title: "WHO Child Growth Standards", publisher: "World Health Organization", tag: "Tăng trưởng trẻ em", note: "Nguồn chuẩn tăng trưởng dùng để tham khảo các chỉ số Z-score ở trẻ nhỏ. Kết quả trong phiếu chỉ là hỗ trợ sàng lọc, cần được nhân viên y tế diễn giải theo hoàn cảnh lâm sàng.", href: "https://www.who.int/tools/child-growth-standards" },
];

export default function ReferencesPage() {
  return <div className="mx-auto flex max-w-6xl flex-col gap-5">
    <section className="border-b-2 border-[#123c36] pb-5"><p className="text-xs font-semibold tracking-[.16em] text-[#123c36]">CĂN CỨ VÀ TÀI LIỆU CHUYÊN MÔN</p><h1 className="mt-1 text-3xl font-semibold">Tài liệu tham khảo</h1><p className="mt-2 max-w-4xl text-neutral-900">Danh mục để người dùng, bác sĩ và dinh dưỡng viên kiểm tra căn cứ của công cụ. Liên kết mở sang trang của cơ quan ban hành hoặc nhà xuất bản; không thay thế việc kiểm tra bản gốc còn hiệu lực.</p></section>
    <aside className="rounded-xl border-2 border-[#a77b10] bg-[#fff9e8] p-5 text-neutral-950"><h2 className="text-xl font-semibold">Lưu ý về tên “Dinh dưỡng 2597”</h2><p className="mt-2">“Dinh dưỡng 2597” là tên của dự án/công cụ này, <b>không phải</b> số hiệu một quy trình hoặc văn bản do Bộ Y tế ban hành. Văn bản chuyên môn liên quan trực tiếp hiện nay là <b>QĐ 2598/QĐ-BYT</b> về Hướng dẫn quy trình kỹ thuật Dinh dưỡng lâm sàng.</p></aside>
    <section className="overflow-hidden rounded-xl border-2 border-[#123c36] bg-white"><div className="border-b-2 border-[#123c36] bg-[#edf4f0] px-5 py-4"><h2 className="text-xl font-semibold">Danh mục tài liệu</h2></div><div className="divide-y-2 divide-[#d0dbd6]">{references.map((item) => <article id={item.tag === "Nhu cầu dinh dưỡng" ? "nhu-cau-dinh-duong" : undefined} key={item.title} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="inline-block rounded-full border border-[#52786d] bg-[#f7faf8] px-2 py-0.5 text-xs font-semibold text-[#123c36]">{item.tag}</span><h3 className="mt-2 text-xl font-semibold">{item.title}</h3><p className="mt-1 font-semibold text-neutral-800">{item.publisher}</p></div><a href={item.href} target="_blank" rel="noreferrer" className="shrink-0 rounded-md border-2 border-[#123c36] px-4 py-2 font-semibold text-[#123c36] hover:bg-[#edf4f0]">Mở tài liệu ↗</a></div><p className="mt-3 max-w-4xl text-neutral-900">{item.note}</p></article>)}</div></section>
    <section className="rounded-xl border-2 border-[#7f948d] bg-[#f7faf8] p-5"><h2 className="text-xl font-semibold">Phạm vi dùng trong website</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-neutral-900"><li>Bảng thành phần thực phẩm, khuyến nghị và chuẩn tăng trưởng phục vụ đối chiếu; mỗi nguồn có phạm vi áp dụng riêng.</li><li>Không suy diễn một hướng dẫn kỹ thuật thành chẩn đoán, kê đơn hoặc chỉ định điều trị cá thể.</li><li>Phiên bản PDF người quản trị lưu để đối chiếu nội bộ không tự động trở thành nguồn công bố chính thức; ưu tiên liên kết nguồn ban hành khi có.</li></ul></section>
    <div><Link href="/ve-he-thong" className="rounded-md bg-[#123c36] px-4 py-2.5 font-semibold text-white">Xem phạm vi hệ thống</Link></div>
  </div>;
}
