-- CreateTable
CREATE TABLE "foods" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "sourceCode" TEXT,
    "sourceNote" TEXT,
    "unit" TEXT NOT NULL DEFAULT 'g',
    "wastePercent" DOUBLE PRECISION,
    "foodType" TEXT,
    "foodGroup" TEXT,
    "proteinOrigin" TEXT,
    "giLevel" INTEGER,
    "purinLevel" INTEGER,
    "cholesterolLevel" INTEGER,
    "vddGroupRaw" TEXT,
    "vddGroupEn" TEXT,
    "energyKcal" DOUBLE PRECISION,
    "energyKj" DOUBLE PRECISION,
    "waterG" DOUBLE PRECISION,
    "proteinG" DOUBLE PRECISION,
    "animalProteinG" DOUBLE PRECISION,
    "lipidG" DOUBLE PRECISION,
    "glucidG" DOUBLE PRECISION,
    "fiberG" DOUBLE PRECISION,
    "ashG" DOUBLE PRECISION,
    "calciumMg" DOUBLE PRECISION,
    "ironMg" DOUBLE PRECISION,
    "magnesiumMg" DOUBLE PRECISION,
    "manganeseMg" DOUBLE PRECISION,
    "phosphorusMg" DOUBLE PRECISION,
    "potassiumMg" DOUBLE PRECISION,
    "sodiumMg" DOUBLE PRECISION,
    "zincMg" DOUBLE PRECISION,
    "copperMgVdd" DOUBLE PRECISION,
    "copperMcgRni" DOUBLE PRECISION,
    "seleniumMcg" DOUBLE PRECISION,
    "fluorideMcg" DOUBLE PRECISION,
    "phytosterolsMg" DOUBLE PRECISION,
    "purinMg" DOUBLE PRECISION,
    "retinolMcg" DOUBLE PRECISION,
    "vitARaeMcg" DOUBLE PRECISION,
    "vitAMgVdd" DOUBLE PRECISION,
    "vitAMcgRni" DOUBLE PRECISION,
    "vitAReMcg" DOUBLE PRECISION,
    "betaCarotenMcg" DOUBLE PRECISION,
    "alphaCarotenMcg" DOUBLE PRECISION,
    "cryptoxanthinBetaMcg" DOUBLE PRECISION,
    "lycopeneMcg" DOUBLE PRECISION,
    "luteinZeaxanthinMcg" DOUBLE PRECISION,
    "vitCMg" DOUBLE PRECISION,
    "vitB1Mg" DOUBLE PRECISION,
    "vitB2Mg" DOUBLE PRECISION,
    "vitB3Mg" DOUBLE PRECISION,
    "niacinEquivMg" DOUBLE PRECISION,
    "vitB5Mg" DOUBLE PRECISION,
    "vitB6Mg" DOUBLE PRECISION,
    "folateTotalMcg" DOUBLE PRECISION,
    "folateFoodMcg" DOUBLE PRECISION,
    "folateDfeMcg" DOUBLE PRECISION,
    "folicAcidMcg" DOUBLE PRECISION,
    "vitB12Mcg" DOUBLE PRECISION,
    "vitB12AddedMcg" DOUBLE PRECISION,
    "biotinMcg" DOUBLE PRECISION,
    "vitDMcg" DOUBLE PRECISION,
    "vitD2Mcg" DOUBLE PRECISION,
    "vitD3Mcg" DOUBLE PRECISION,
    "vitEMg" DOUBLE PRECISION,
    "vitEAddedMg" DOUBLE PRECISION,
    "tocopherolAlphaMg" DOUBLE PRECISION,
    "tocopherolBetaMg" DOUBLE PRECISION,
    "tocopherolGammaMg" DOUBLE PRECISION,
    "tocopherolDeltaMg" DOUBLE PRECISION,
    "tocotrienolAlphaMg" DOUBLE PRECISION,
    "tocotrienolBetaMg" DOUBLE PRECISION,
    "tocotrienolGammaMg" DOUBLE PRECISION,
    "tocotrienolDeltaMg" DOUBLE PRECISION,
    "vitKMcg" DOUBLE PRECISION,
    "dihydrophylloquinoneMcg" DOUBLE PRECISION,
    "menaquinone4Mcg" DOUBLE PRECISION,
    "cholineMg" DOUBLE PRECISION,
    "tryptophanMg" DOUBLE PRECISION,
    "threonineMg" DOUBLE PRECISION,
    "isoleucineMg" DOUBLE PRECISION,
    "leucineMg" DOUBLE PRECISION,
    "lysineMg" DOUBLE PRECISION,
    "methionineMg" DOUBLE PRECISION,
    "cystineMg" DOUBLE PRECISION,
    "phenylalanineMg" DOUBLE PRECISION,
    "tyrosineMg" DOUBLE PRECISION,
    "valineMg" DOUBLE PRECISION,
    "arginineMg" DOUBLE PRECISION,
    "histidineMg" DOUBLE PRECISION,
    "alanineMg" DOUBLE PRECISION,
    "asparticAcidMg" DOUBLE PRECISION,
    "glutamicAcidMg" DOUBLE PRECISION,
    "glycineMg" DOUBLE PRECISION,
    "prolineMg" DOUBLE PRECISION,
    "serineMg" DOUBLE PRECISION,
    "hydroxyprolineG" DOUBLE PRECISION,
    "satFatTotalG" DOUBLE PRECISION,
    "palmiticC160G" DOUBLE PRECISION,
    "margaricC170G" DOUBLE PRECISION,
    "stearicC180G" DOUBLE PRECISION,
    "behenicC220G" DOUBLE PRECISION,
    "lignocericC240G" DOUBLE PRECISION,
    "mufaTotalG" DOUBLE PRECISION,
    "myristoleicC141G" DOUBLE PRECISION,
    "palmitoleicC161G" DOUBLE PRECISION,
    "oleicC181G" DOUBLE PRECISION,
    "pufaTotalG" DOUBLE PRECISION,
    "linoleicC182G" DOUBLE PRECISION,
    "linolenicC183G" DOUBLE PRECISION,
    "arachidonicC204G" DOUBLE PRECISION,
    "epaC205G" DOUBLE PRECISION,
    "dhaC226G" DOUBLE PRECISION,
    "cholesterolMg" DOUBLE PRECISION,
    "transFatTotalG" DOUBLE PRECISION,
    "rniUnknownFattyAcidG" DOUBLE PRECISION,
    "c40G" DOUBLE PRECISION,
    "c60G" DOUBLE PRECISION,
    "c80G" DOUBLE PRECISION,
    "c100G" DOUBLE PRECISION,
    "c120G" DOUBLE PRECISION,
    "c140G" DOUBLE PRECISION,
    "c181UndiffG" DOUBLE PRECISION,
    "c161UndiffG" DOUBLE PRECISION,
    "c182UndiffG" DOUBLE PRECISION,
    "c183UndiffG" DOUBLE PRECISION,
    "c200G" DOUBLE PRECISION,
    "c130G" DOUBLE PRECISION,
    "c150G" DOUBLE PRECISION,
    "c151G" DOUBLE PRECISION,
    "c161TransG" DOUBLE PRECISION,
    "c171G" DOUBLE PRECISION,
    "c181TransG" DOUBLE PRECISION,
    "c1811TransG" DOUBLE PRECISION,
    "c201G" DOUBLE PRECISION,
    "c221UndiffG" DOUBLE PRECISION,
    "c221cG" DOUBLE PRECISION,
    "c221tG" DOUBLE PRECISION,
    "c241cG" DOUBLE PRECISION,
    "c182ClaG" DOUBLE PRECISION,
    "c182TtG" DOUBLE PRECISION,
    "c182IG" DOUBLE PRECISION,
    "c182NfdG" DOUBLE PRECISION,
    "c183N6CccG" DOUBLE PRECISION,
    "c183IG" DOUBLE PRECISION,
    "c184G" DOUBLE PRECISION,
    "c202N6CcG" DOUBLE PRECISION,
    "c203UndiffG" DOUBLE PRECISION,
    "c203N3G" DOUBLE PRECISION,
    "c203N6G" DOUBLE PRECISION,
    "c204UndiffG" DOUBLE PRECISION,
    "c215G" DOUBLE PRECISION,
    "c224G" DOUBLE PRECISION,
    "c225N3DpaG" DOUBLE PRECISION,
    "transMonoenoicG" DOUBLE PRECISION,
    "transPolyenoicG" DOUBLE PRECISION,
    "stigmasterolMg" DOUBLE PRECISION,
    "campesterolMg" DOUBLE PRECISION,
    "betaSitosterolMg" DOUBLE PRECISION,
    "sugarsTotalG" DOUBLE PRECISION,
    "glucoseG" DOUBLE PRECISION,
    "fructoseG" DOUBLE PRECISION,
    "lactoseG" DOUBLE PRECISION,
    "maltoseG" DOUBLE PRECISION,
    "galactoseG" DOUBLE PRECISION,
    "sucroseG" DOUBLE PRECISION,
    "starchG" DOUBLE PRECISION,
    "phyticAcidMg" DOUBLE PRECISION,
    "sugarsAddedG" DOUBLE PRECISION,
    "caffeineMg" DOUBLE PRECISION,
    "theobromineMg" DOUBLE PRECISION,
    "alcoholG" DOUBLE PRECISION,
    "isoflavoneTotalMg" DOUBLE PRECISION,
    "daidzeinMg" DOUBLE PRECISION,
    "genisteinMg" DOUBLE PRECISION,
    "glyceteinMg" DOUBLE PRECISION,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "foods_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "dishes" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "sourceCode" TEXT,
    "totalWeightG" DOUBLE PRECISION,
    "servingUnit" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "categoryRaw" TEXT,
    "diseaseDiet" TEXT,
    "ageGroup" TEXT,
    "cookingSteps" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "dishes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "dish_ingredients" (
    "id" TEXT NOT NULL,
    "dishId" TEXT NOT NULL,
    "foodNameRaw" TEXT NOT NULL,
    "foodId" TEXT,
    "quantityG" DOUBLE PRECISION,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "dish_ingredients_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "foods_name_idx" ON "foods"("name");

-- CreateIndex
CREATE INDEX "foods_source_idx" ON "foods"("source");

-- CreateIndex
CREATE INDEX "foods_foodGroup_idx" ON "foods"("foodGroup");

-- CreateIndex
CREATE INDEX "dishes_name_idx" ON "dishes"("name");

-- CreateIndex
CREATE INDEX "dishes_diseaseDiet_idx" ON "dishes"("diseaseDiet");

-- CreateIndex
CREATE INDEX "dish_ingredients_dishId_idx" ON "dish_ingredients"("dishId");

-- CreateIndex
CREATE INDEX "dish_ingredients_foodId_idx" ON "dish_ingredients"("foodId");

-- AddForeignKey
ALTER TABLE "dish_ingredients" ADD CONSTRAINT "dish_ingredients_dishId_fkey" FOREIGN KEY ("dishId") REFERENCES "dishes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dish_ingredients" ADD CONSTRAINT "dish_ingredients_foodId_fkey" FOREIGN KEY ("foodId") REFERENCES "foods"("id") ON DELETE SET NULL ON UPDATE CASCADE;
